In [1]:
# Importing libraries

import glob
import numpy as np
import pandas as pd

In [2]:
# Merging CSV's
csv_files = glob.glob('/home/fungazi/Projects/DroidF_actory/EntraID Triaging/entra_signin_logs_part*.csv')

dfs = []

for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)

merged_df.to_csv('EntraID_logs.csv', index=False)

/tmp/ipykernel_6570/2329978216.py:7: DtypeWarning: Columns (72: GT_Stage) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

In [3]:
# Sort by time and reset index

cols = ['TimeGenerated','CreatedDateTime']
entra_df = pd.read_csv(r"/home/fungazi/Projects/DroidF_actory/EntraID Triaging/EntraID_logs.csv")

entra_df[cols] = entra_df[cols].apply(pd.to_datetime, format='%Y-%m-%dT%H:%M:%S.%fZ', utc=True)

entra_df = entra_df.sort_values('TimeGenerated')

entra_df = entra_df.reset_index(drop=True)

entra_df

,TimeGenerated,CreatedDateTime,Type,Category,OperationName,OperationVersion,Level,ResourceProvider,SourceSystem,AADTenantId,...,RiskLevelAggregated,RiskLevelDuringSignIn,RiskState,FlaggedForReview,IsTenantRestricted,IsThroughGlobalSecureAccess,GT_Label,GT_ScenarioId,GT_ScenarioName,GT_Stage
0,2026-08-21 11:03:42.392000+00:00,2026-08-21 11:03:42.392000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
1,2026-08-21 11:04:58.676000+00:00,2026-08-21 11:04:58.676000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
2,2026-08-21 11:05:56.829000+00:00,2026-08-21 11:05:56.829000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
3,2026-08-21 11:08:09.250000+00:00,2026-08-21 11:08:09.250000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
4,2026-08-21 11:11:40.504000+00:00,2026-08-21 11:11:40.504000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47119,2026-09-20 00:54:42.655000+00:00,2026-09-20 00:54:42.655000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
47120,2026-09-20 01:01:37.972000+00:00,2026-09-20 01:01:37.972000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
47121,2026-09-20 01:09:26.947000+00:00,2026-09-20 01:09:26.947000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
47122,2026-09-20 01:17:03.927000+00:00,2026-09-20 01:17:03.927000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN
47123,2026-09-20 01:27:50.069000+00:00,2026-09-20 01:27:50.069000+00:00,AADNonInteractiveUserSignInLogs,NonInteractiveUserSignInLogs,Sign-in activity,1.0,4,AAD,Azure AD,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,...,none,none,none,False,False,False,benign,NaN,NaN,NaN

In [4]:
# Finding missing values

entra_df.isnull()

,TimeGenerated,CreatedDateTime,Type,Category,OperationName,OperationVersion,Level,ResourceProvider,SourceSystem,AADTenantId,...,RiskLevelAggregated,RiskLevelDuringSignIn,RiskState,FlaggedForReview,IsTenantRestricted,IsThroughGlobalSecureAccess,GT_Label,GT_ScenarioId,GT_ScenarioName,GT_Stage
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47119,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
47120,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
47121,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
47122,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
47123,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True

In [6]:
list(entra_df)

['TimeGenerated',
 'CreatedDateTime',
 'Type',
 'Category',
 'OperationName',
 'OperationVersion',
 'Level',
 'ResourceProvider',
 'SourceSystem',
 'AADTenantId',
 'Id',
 'CorrelationId',
 'OriginalRequestId',
 'SessionId',
 'UniqueTokenIdentifier',
 'UserId',
 'UserPrincipalName',
 'UserDisplayName',
 'Identity',
 'UserType',
 'SignInIdentifier',
 'SignInIdentifierType',
 'AlternateSignInName',
 'HomeTenantId',
 'ResourceTenantId',
 'ResourceOwnerTenantId',
 'CrossTenantAccessType',
 'AppId',
 'AppDisplayName',
 'AppOwnerTenantId',
 'ResourceIdentity',
 'ResourceDisplayName',
 'ResourceServicePrincipalId',
 'ClientAppUsed',
 'AuthenticationProtocol',
 'IsInteractive',
 'IncomingTokenType',
 'TokenIssuerType',
 'TokenIssuerName',
 'IPAddress',
 'Location',
 'LocationDetails',
 'AutonomousSystemNumber',
 'NetworkLocationDetails',
 'DeviceDetail',
 'UserAgent',
 'ResultType',
 'ResultSignature',
 'ResultDescription',
 'Status',
 'DurationMs',
 'ProcessingTimeInMilliseconds',
 'AuthenticationRequirement',
 'AuthenticationRequirementPolicies',
 'AuthenticationMethodsUsed',
 'AuthenticationDetails',
 'ConditionalAccessStatus',
 'ConditionalAccessPolicies',
 'SessionLifetimePolicies',
 'ClientCredentialType',
 'IsRisky',
 'RiskDetail',
 'RiskEventTypes_V2',
 'RiskLevelAggregated',
 'RiskLevelDuringSignIn',
 'RiskState',
 'FlaggedForReview',
 'IsTenantRestricted',
 'IsThroughGlobalSecureAccess',
 'GT_Label',
 'GT_ScenarioId',
 'GT_ScenarioName',
 'GT_Stage']

In [31]:
# Possible Columns Identifying malicious activity

possibleColumns_df = entra_df[['TimeGenerated','CreatedDateTime','Type','AADTenantId','UserId','UserPrincipalName','UserDisplayName','UserType','ResourceOwnerTenantId','AppId','AppDisplayName','AppOwnerTenantId','ResourceIdentity','ResourceDisplayName','ResourceServicePrincipalId','ClientAppUsed','AuthenticationProtocol','IsInteractive','IncomingTokenType','IPAddress','Location','LocationDetails','UserAgent','ResultType','ResultDescription','IsRisky','RiskEventTypes_V2','RiskLevelAggregated','RiskLevelDuringSignIn','GT_Label','GT_ScenarioId','GT_ScenarioName','GT_Stage']]

possibleColumns_df

,TimeGenerated,CreatedDateTime,Type,AADTenantId,UserId,UserPrincipalName,UserDisplayName,UserType,ResourceOwnerTenantId,AppId,...,ResultType,ResultDescription,IsRisky,RiskEventTypes_V2,RiskLevelAggregated,RiskLevelDuringSignIn,GT_Label,GT_ScenarioId,GT_ScenarioName,GT_Stage
0,2026-08-21 11:03:42.392000+00:00,2026-08-21 11:03:42.392000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,5d7611cc-0cee-4826-8872-40d106caaa08,colleen.bruno@harborviewcpa.com,Colleen Bruno,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
1,2026-08-21 11:04:58.676000+00:00,2026-08-21 11:04:58.676000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,2cb6ca39-4460-4d07-8040-60ad6a7edce6,brian.russo@harborviewcpa.com,Brian Russo,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
2,2026-08-21 11:05:56.829000+00:00,2026-08-21 11:05:56.829000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,898f310e-2763-49f2-8b21-1af8736ca844,wyatt.wang@harborviewcpa.com,Wyatt Wang,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,1fec8e78-bce4-4aaf-ab1b-5451cc387264,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
3,2026-08-21 11:08:09.250000+00:00,2026-08-21 11:08:09.250000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,436fdb21-b98d-48a1-b683-938846d4c440,chloe.gupta@harborviewcpa.com,Chloe Gupta,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
4,2026-08-21 11:11:40.504000+00:00,2026-08-21 11:11:40.504000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,fced3ece-948c-4dc2-9bad-24c9233a3fcb,gregory.morales@harborviewcpa.com,Gregory Morales,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,1fec8e78-bce4-4aaf-ab1b-5451cc387264,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47119,2026-09-20 00:54:42.655000+00:00,2026-09-20 00:54:42.655000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,32724257-45e9-4776-8f63-bfb3abd1c10f,rajesh.obrien@harborviewcpa.com,Rajesh O'Brien,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
47120,2026-09-20 01:01:37.972000+00:00,2026-09-20 01:01:37.972000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,26edf2fa-1bd6-4718-9ce1-6b522dc01e0e,chloe.burke@harborviewcpa.com,Chloe Burke,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,1fec8e78-bce4-4aaf-ab1b-5451cc387264,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
47121,2026-09-20 01:09:26.947000+00:00,2026-09-20 01:09:26.947000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,7337a146-cc46-4472-85a8-d53dba00a5d1,sean.kelly@harborviewcpa.com,Sean Kelly,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
47122,2026-09-20 01:17:03.927000+00:00,2026-09-20 01:17:03.927000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,c9b65aa3-ce14-45b4-a03a-602d231d2cb2,chloe.hale@harborviewcpa.com,Chloe Hale,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN
47123,2026-09-20 01:27:50.069000+00:00,2026-09-20 01:27:50.069000+00:00,AADNonInteractiveUserSignInLogs,3f6b1c2e-8d4a-4e57-9b0a-6c2d5e7f1a90,e6b293aa-27f1-459b-9eff-158153f426b5,kevin.sullivan@harborviewcpa.com,Kevin Sullivan,Member,f8cdef31-a31e-4b4a-93e4-5f571e91255a,27922004-5251-4030-b22d-91ecd9a37ea4,...,0,NaN,False,[],none,none,benign,NaN,NaN,NaN